require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/occupations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Occupation. As you add validations to Occupation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Occupation.create! valid_attributes
      get occupations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      occupation = Occupation.create! valid_attributes
      get occupation_url(occupation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_occupation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      occupation = Occupation.create! valid_attributes
      get edit_occupation_url(occupation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Occupation" do
        expect {
          post occupations_url, params: { occupation: valid_attributes }
        }.to change(Occupation, :count).by(1)
      end

      it "redirects to the created occupation" do
        post occupations_url, params: { occupation: valid_attributes }
        expect(response).to redirect_to(occupation_url(Occupation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Occupation" do
        expect {
          post occupations_url, params: { occupation: invalid_attributes }
        }.to change(Occupation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post occupations_url, params: { occupation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested occupation" do
        occupation = Occupation.create! valid_attributes
        patch occupation_url(occupation), params: { occupation: new_attributes }
        occupation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the occupation" do
        occupation = Occupation.create! valid_attributes
        patch occupation_url(occupation), params: { occupation: new_attributes }
        occupation.reload
        expect(response).to redirect_to(occupation_url(occupation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        occupation = Occupation.create! valid_attributes
        patch occupation_url(occupation), params: { occupation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested occupation" do
      occupation = Occupation.create! valid_attributes
      expect {
        delete occupation_url(occupation)
      }.to change(Occupation, :count).by(-1)
    end

    it "redirects to the occupations list" do
      occupation = Occupation.create! valid_attributes
      delete occupation_url(occupation)
      expect(response).to redirect_to(occupations_url)
    end
  end
end
