require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rewards_earned_lists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RewardsEarnedList. As you add validations to RewardsEarnedList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RewardsEarnedList.create! valid_attributes
      get rewards_earned_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rewards_earned_list = RewardsEarnedList.create! valid_attributes
      get rewards_earned_list_url(rewards_earned_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rewards_earned_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      rewards_earned_list = RewardsEarnedList.create! valid_attributes
      get edit_rewards_earned_list_url(rewards_earned_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RewardsEarnedList" do
        expect {
          post rewards_earned_lists_url, params: { rewards_earned_list: valid_attributes }
        }.to change(RewardsEarnedList, :count).by(1)
      end

      it "redirects to the created rewards_earned_list" do
        post rewards_earned_lists_url, params: { rewards_earned_list: valid_attributes }
        expect(response).to redirect_to(rewards_earned_list_url(RewardsEarnedList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RewardsEarnedList" do
        expect {
          post rewards_earned_lists_url, params: { rewards_earned_list: invalid_attributes }
        }.to change(RewardsEarnedList, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rewards_earned_lists_url, params: { rewards_earned_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rewards_earned_list" do
        rewards_earned_list = RewardsEarnedList.create! valid_attributes
        patch rewards_earned_list_url(rewards_earned_list), params: { rewards_earned_list: new_attributes }
        rewards_earned_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rewards_earned_list" do
        rewards_earned_list = RewardsEarnedList.create! valid_attributes
        patch rewards_earned_list_url(rewards_earned_list), params: { rewards_earned_list: new_attributes }
        rewards_earned_list.reload
        expect(response).to redirect_to(rewards_earned_list_url(rewards_earned_list))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rewards_earned_list = RewardsEarnedList.create! valid_attributes
        patch rewards_earned_list_url(rewards_earned_list), params: { rewards_earned_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rewards_earned_list" do
      rewards_earned_list = RewardsEarnedList.create! valid_attributes
      expect {
        delete rewards_earned_list_url(rewards_earned_list)
      }.to change(RewardsEarnedList, :count).by(-1)
    end

    it "redirects to the rewards_earned_lists list" do
      rewards_earned_list = RewardsEarnedList.create! valid_attributes
      delete rewards_earned_list_url(rewards_earned_list)
      expect(response).to redirect_to(rewards_earned_lists_url)
    end
  end
end
