require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rewards_approval_lists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RewardsApprovalList. As you add validations to RewardsApprovalList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RewardsApprovalList.create! valid_attributes
      get rewards_approval_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rewards_approval_list = RewardsApprovalList.create! valid_attributes
      get rewards_approval_list_url(rewards_approval_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rewards_approval_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      rewards_approval_list = RewardsApprovalList.create! valid_attributes
      get edit_rewards_approval_list_url(rewards_approval_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RewardsApprovalList" do
        expect {
          post rewards_approval_lists_url, params: { rewards_approval_list: valid_attributes }
        }.to change(RewardsApprovalList, :count).by(1)
      end

      it "redirects to the created rewards_approval_list" do
        post rewards_approval_lists_url, params: { rewards_approval_list: valid_attributes }
        expect(response).to redirect_to(rewards_approval_list_url(RewardsApprovalList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RewardsApprovalList" do
        expect {
          post rewards_approval_lists_url, params: { rewards_approval_list: invalid_attributes }
        }.to change(RewardsApprovalList, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rewards_approval_lists_url, params: { rewards_approval_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rewards_approval_list" do
        rewards_approval_list = RewardsApprovalList.create! valid_attributes
        patch rewards_approval_list_url(rewards_approval_list), params: { rewards_approval_list: new_attributes }
        rewards_approval_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rewards_approval_list" do
        rewards_approval_list = RewardsApprovalList.create! valid_attributes
        patch rewards_approval_list_url(rewards_approval_list), params: { rewards_approval_list: new_attributes }
        rewards_approval_list.reload
        expect(response).to redirect_to(rewards_approval_list_url(rewards_approval_list))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rewards_approval_list = RewardsApprovalList.create! valid_attributes
        patch rewards_approval_list_url(rewards_approval_list), params: { rewards_approval_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rewards_approval_list" do
      rewards_approval_list = RewardsApprovalList.create! valid_attributes
      expect {
        delete rewards_approval_list_url(rewards_approval_list)
      }.to change(RewardsApprovalList, :count).by(-1)
    end

    it "redirects to the rewards_approval_lists list" do
      rewards_approval_list = RewardsApprovalList.create! valid_attributes
      delete rewards_approval_list_url(rewards_approval_list)
      expect(response).to redirect_to(rewards_approval_lists_url)
    end
  end
end
